### ISSUE TITLE
Unhandled response: RequestLimitExceeded

### ISSUE THREAD

**Issue by kerma** [danihodovic/generate-ssh-configs#3]
My first test run against my production AWS account resulted in panic. AWS limits requests, but it's an hard thing to hit. You might want to check/limit this somehow. Or handle the error response properly. 

```
panic: RequestLimitExceeded: Request limit exceeded.
	status code: 503, request id: c8d70a14-7ee6-4110-9772-d7aaab8a6a25

goroutine 1 [running]:
main.isInstanceInPublicSubnet(0xc0000a00b8, 0xc0007e6680, 0x17a4ba9)
	/Users/margus/src/go/src/github.com/danihodovic/generate-ssh-configs/aws.go:155 +0x4f9
main.generateAWS(0xc0000968a7, 0x5)
	/Users/margus/src/go/src/github.com/danihodovic/generate-ssh-configs/aws.go:285 +0x513
main.glob..func2(0x1dbbde0, 0xc0000a6d20, 0x0, 0x2)
	/Users/margus/src/go/src/github.com/danihodovic/generate-ssh-configs/cmd.go:29 +0x47
github.com/spf13/cobra.(*Command).execute(0x1dbbde0, 0xc0000a6d00, 0x2, 0x2, 0x1dbbde0, 0xc0000a6d00)
	/Users/margus/src/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1dbbb80, 0x14, 0x1dbc040, 0x1dbbde0)
	/Users/margus/src/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1dbbb80, 0x0, 0x17a60c6)
	/Users/margus/src/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/margus/src/go/src/github.com/danihodovic/generate-ssh-configs/main.go:16 +0x36
```

**Comment by kerma** [comment]
I looked into this a little bit more. It seems, that `aws.Client` has a "built-in" retry mechanism, but the default configuration uses _service specific configuration_. This probably is not working nicely for ec2, so implicitly setting retry count to something reasonable seems to work.

https://github.com/danihodovic/generate-ssh-configs/blob/f431fabb183717dbc634f9502580588426e159a7/aws.go#L238

This worked for me:

```
ec2Client := ec2.New(sess, &aws.Config{MaxRetries: aws.Int(5)})
```
